#!/usr/bin/env python3

import os.path

import biblib.bib
import biblib.messages
import biblib.algo
import argparse
import shutil
import sys
import re

MONTHS = 'January February March April May June July August September October November December'.split()

def main():
    arg_parser = argparse.ArgumentParser(
        description='Parse .bib database(s) and print basic fields as text')
    arg_parser.add_argument('--bib', nargs=1, help='.bib file(s) to process',
                            type=open)
    arg_parser.add_argument('--pdf', nargs=1, help='.pdf file to rename',
                            type=open)
    args = arg_parser.parse_args()

    try:
        # Load databases
        db = biblib.bib.Parser().parse(args.bib, log_fp=sys.stderr).get_entries()

        # Resolve cross-references
        db = biblib.bib.resolve_crossrefs(db)

        # Print entries
        recoverer = biblib.messages.InputErrorRecoverer()
        for ent in db.values():
            with recoverer:
                rename_file(ent, args.pdf)
        recoverer.reraise()
    except biblib.messages.InputError:
        sys.exit(1)

def rename_file(ent, pdf):
    if 'author' in ent:
        authors = [
            biblib.algo.tex_to_unicode(author.last,
                                       pos=ent.field_pos['author'])
            for author in ent.authors()]
        if len(authors) == 0:
            author = None
        elif len(authors) == 1:
            author = authors[0]
        else:
            author = ', '.join(authors[:-1])
            if len(authors) > 2:
                author += ','
            if ent.authors()[-1].is_others():
                author += ' et al.'
            else:
                author += ' and ' + authors[-1]


    if author and 'year' in ent and 'title' in ent:
        newname = author + ' - ' + '{}'.format(ent['year']) + ' - ' + biblib.algo.tex_to_unicode(biblib.algo.title_case(ent['title'], pos=ent.field_pos['title'])).replace("/", " ") + '.pdf'

        if os.path.exists(pdf[0].name):
            shutil.copy2(pdf[0].name, os.getcwd() + '/' +  newname)


if __name__ == '__main__':
    main()
